package com.noxmedical.blescanner.utils;

import android.util.SparseArray;


public class BluetoothSigConsts {
    /**
     * Copied from https://www.bluetooth.com/specifications/assigned-numbers/company-Identifiers
     * and https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile
     * NOTE: That page has funny "zero-width-spaces"
     */
    public final static SparseArray<String> companyMap = new SparseArray<>();
    public final static SparseArray<String> segmentTypeMap = new SparseArray<>();
    static {

        segmentTypeMap.put(0x01, "Flags");
        segmentTypeMap.put(0x02, "Incomplete List of 16-bit Service Class UUIDs");
        segmentTypeMap.put(0x03, "Complete List of 16-bit Service Class UUIDs");
        segmentTypeMap.put(0x04, "Incomplete List of 32-bit Service Class UUIDs");
        segmentTypeMap.put(0x05, "Complete List of 32-bit Service Class UUIDs");
        segmentTypeMap.put(0x06, "Incomplete List of 128-bit Service Class UUIDs");
        segmentTypeMap.put(0x07, "Complete List of 128-bit Service Class UUIDs");
        segmentTypeMap.put(0x08, "Shortened Local Name");
        segmentTypeMap.put(0x09, "Complete Local Name");
        segmentTypeMap.put(0x0A, "Tx Power Level");
        segmentTypeMap.put(0x0D, "Class of Device");
        segmentTypeMap.put(0x0E, "Simple Pairing Hash C");
        segmentTypeMap.put(0x0E, "Simple Pairing Hash C-192");
        segmentTypeMap.put(0x0F, "Simple Pairing Randomizer R");
        segmentTypeMap.put(0x0F, "Simple Pairing Randomizer R-192");
        segmentTypeMap.put(0x10, "Device ID");
        segmentTypeMap.put(0x10, "Security Manager TK Value");
        segmentTypeMap.put(0x11, "Security Manager Out of Band Flags");
        segmentTypeMap.put(0x12, "Slave Connection Interval Range");
        segmentTypeMap.put(0x14, "List of 16-bit Service Solicitation UUIDs");
        segmentTypeMap.put(0x1F, "List of 32-bit Service Solicitation UUIDs");
        segmentTypeMap.put(0x15, "List of 128-bit Service Solicitation UUIDs");
        segmentTypeMap.put(0x16, "Service Data");
        segmentTypeMap.put(0x16, "Service Data - 16-bit UUID");
        segmentTypeMap.put(0x20, "Service Data - 32-bit UUID");
        segmentTypeMap.put(0x21, "Service Data - 128-bit UUID");
        segmentTypeMap.put(0x22, "LE Secure Connections Confirmation Value");
        segmentTypeMap.put(0x23, "LE Secure Connections Random Value");
        segmentTypeMap.put(0x24, "URI");
        segmentTypeMap.put(0x25, "Indoor Positioning");
        segmentTypeMap.put(0x26, "Transport Discovery Data");
        segmentTypeMap.put(0x17, "Public Target Address");
        segmentTypeMap.put(0x18, "Random Target Address");
        segmentTypeMap.put(0x19, "Appearance");
        segmentTypeMap.put(0x1A, "Advertising Interval");
        segmentTypeMap.put(0x1B, "LE Bluetooth Device Address");
        segmentTypeMap.put(0x1C, "LE Role");
        segmentTypeMap.put(0x1D, "Simple Pairing Hash C-256");
        segmentTypeMap.put(0x1E, "Simple Pairing Randomizer R-256");
        segmentTypeMap.put(0x3D, "3D Information Data");
        segmentTypeMap.put(0xFF, "Manufacturer Specific Data");
        
        companyMap.put(0x0000, "Ericsson Technology Licensing");
        companyMap.put(0x0001, "Nokia Mobile Phones");
        companyMap.put(0x0002, "Intel Corp.");
        companyMap.put(0x0003, "IBM Corp.");
        companyMap.put(0x0004, "Toshiba Corp.");
        companyMap.put(0x0005, "3Com");
        companyMap.put(0x0006, "Microsoft");
        companyMap.put(0x0007, "Lucent");
        companyMap.put(0x0008, "Motorola");
        companyMap.put(0x0009, "Infineon Technologies AG");
        companyMap.put(0x000A, "Cambridge Silicon Radio");
        companyMap.put(0x000B, "Silicon Wave");
        companyMap.put(0x000C, "Digianswer A/S");
        companyMap.put(0x000D, "Texas Instruments Inc.");
        companyMap.put(0x000E, "Ceva, Inc. (formerly Parthus Technologies, Inc.)");
        companyMap.put(0x000F, "Broadcom Corporation");
        companyMap.put(0x0010, "Mitel Semiconductor");
        companyMap.put(0x0011, "Widcomm, Inc");
        companyMap.put(0x0012, "Zeevo, Inc.");
        companyMap.put(0x0013, "Atmel Corporation");
        companyMap.put(0x0014, "Mitsubishi Electric Corporation");
        companyMap.put(0x0015, "RTX Telecom A/S");
        companyMap.put(0x0016, "KC Technology Inc.");
        companyMap.put(0x0017, "NewLogic");
        companyMap.put(0x0018, "Transilica, Inc.");
        companyMap.put(0x0019, "Rohde & Schwarz GmbH & Co. KG");
        companyMap.put(0x001A, "TTPCom Limited");
        companyMap.put(0x001B, "Signia Technologies, Inc.");
        companyMap.put(0x001C, "Conexant Systems Inc.");
        companyMap.put(0x001D, "Qualcomm");
        companyMap.put(0x001E, "Inventel");
        companyMap.put(0x001F, "AVM Berlin");
        companyMap.put(0x0020, "BandSpeed, Inc.");
        companyMap.put(0x0021, "Mansella Ltd");
        companyMap.put(0x0022, "NEC Corporation");
        companyMap.put(0x0023, "WavePlus Technology Co., Ltd.");
        companyMap.put(0x0024, "Alcatel");
        companyMap.put(0x0025, "NXP Semiconductors (formerly Philips Semiconductors)");
        companyMap.put(0x0026, "C Technologies");
        companyMap.put(0x0027, "Open Interface");
        companyMap.put(0x0028, "R F Micro Devices");
        companyMap.put(0x0029, "Hitachi Ltd");
        companyMap.put(0x002A, "Symbol Technologies, Inc.");
        companyMap.put(0x002B, "Tenovis");
        companyMap.put(0x002C, "Macronix International Co. Ltd.");
        companyMap.put(0x002D, "GCT Semiconductor");
        companyMap.put(0x002E, "Norwood Systems");
        companyMap.put(0x002F, "MewTel Technology Inc.");
        companyMap.put(0x0030, "ST Microelectronics");
        companyMap.put(0x0031, "Synopsys, Inc.");
        companyMap.put(0x0032, "Red-M (Communications) Ltd");
        companyMap.put(0x0033, "Commil Ltd");
        companyMap.put(0x0034, "Computer Access Technology Corporation (CATC)");
        companyMap.put(0x0035, "Eclipse (HQ Espana) S.L.");
        companyMap.put(0x0036, "Renesas Electronics Corporation");
        companyMap.put(0x0037, "Mobilian Corporation");
        companyMap.put(0x0038, "Terax");
        companyMap.put(0x0039, "Integrated System Solution Corp.");
        companyMap.put(0x003A, "Matsushita Electric Industrial Co., Ltd.");
        companyMap.put(0x003B, "Gennum Corporation");
        companyMap.put(0x003C, "BlackBerry Limited (formerly Research In Motion)");
        companyMap.put(0x003D, "IPextreme, Inc.");
        companyMap.put(0x003E, "Systems and Chips, Inc.");
        companyMap.put(0x003F, "Bluetooth SIG, Inc.");
        companyMap.put(0x0040, "Seiko Epson Corporation");
        companyMap.put(0x0041, "Integrated Silicon Solution Taiwan, Inc.");
        companyMap.put(0x0042, "CONWISE Technology Corporation Ltd");
        companyMap.put(0x0043, "PARROT SA");
        companyMap.put(0x0044, "Socket Mobile");
        companyMap.put(0x0045, "Atheros Communications, Inc.");
        companyMap.put(0x0046, "MediaTek, Inc.");
        companyMap.put(0x0047, "Bluegiga");
        companyMap.put(0x0048, "Marvell Technology Group Ltd.");
        companyMap.put(0x0049, "3DSP Corporation");
        companyMap.put(0x004A, "Accel Semiconductor Ltd.");
        companyMap.put(0x004B, "Continental Automotive Systems");
        companyMap.put(0x004C, "Apple, Inc.");
        companyMap.put(0x004D, "Staccato Communications, Inc.");
        companyMap.put(0x004E, "Avago Technologies");
        companyMap.put(0x004F, "APT Licensing Ltd.");
        companyMap.put(0x0050, "SiRF Technology");
        companyMap.put(0x0051, "Tzero Technologies, Inc.");
        companyMap.put(0x0052, "J&M Corporation");
        companyMap.put(0x0053, "Free2move AB");
        companyMap.put(0x0054, "3DiJoy Corporation");
        companyMap.put(0x0055, "Plantronics, Inc.");
        companyMap.put(0x0056, "Sony Ericsson Mobile Communications");
        companyMap.put(0x0057, "Harman International Industries, Inc.");
        companyMap.put(0x0058, "Vizio, Inc.");
        companyMap.put(0x0059, "Nordic Semiconductor ASA");
        companyMap.put(0x005A, "EM Microelectronic-Marin SA");
        companyMap.put(0x005B, "Ralink Technology Corporation");
        companyMap.put(0x005C, "Belkin International, Inc.");
        companyMap.put(0x005D, "Realtek Semiconductor Corporation");
        companyMap.put(0x005E, "Stonestreet One, LLC");
        companyMap.put(0x005F, "Wicentric, Inc.");
        companyMap.put(0x0060, "RivieraWaves S.A.S");
        companyMap.put(0x0061, "RDA Microelectronics");
        companyMap.put(0x0062, "Gibson Guitars");
        companyMap.put(0x0063, "MiCommand Inc.");
        companyMap.put(0x0064, "Band XI International, LLC");
        companyMap.put(0x0065, "Hewlett-Packard Company");
        companyMap.put(0x0066, "9Solutions Oy");
        companyMap.put(0x0067, "GN Netcom A/S");
        companyMap.put(0x0068, "General Motors");
        companyMap.put(0x0069, "A&D Engineering, Inc.");
        companyMap.put(0x006A, "MindTree Ltd.");
        companyMap.put(0x006B, "Polar Electro OY");
        companyMap.put(0x006C, "Beautiful Enterprise Co., Ltd.");
        companyMap.put(0x006D, "BriarTek, Inc.");
        companyMap.put(0x006E, "Summit Data Communications, Inc.");
        companyMap.put(0x006F, "Sound ID");
        companyMap.put(0x0070, "Monster, LLC");
        companyMap.put(0x0071, "connectBlue AB");
        companyMap.put(0x0072, "ShangHai Super Smart Electronics Co. Ltd.");
        companyMap.put(0x0073, "Group Sense Ltd.");
        companyMap.put(0x0074, "Zomm, LLC");
        companyMap.put(0x0075, "Samsung Electronics Co. Ltd.");
        companyMap.put(0x0076, "Creative Technology Ltd.");
        companyMap.put(0x0077, "Laird Technologies");
        companyMap.put(0x0078, "Nike, Inc.");
        companyMap.put(0x0079, "lesswire AG");
        companyMap.put(0x007A, "MStar Semiconductor, Inc.");
        companyMap.put(0x007B, "Hanlynn Technologies");
        companyMap.put(0x007C, "A & R Cambridge");
        companyMap.put(0x007D, "Seers Technology Co. Ltd");
        companyMap.put(0x007E, "Sports Tracking Technologies Ltd.");
        companyMap.put(0x007F, "Autonet Mobile");
        companyMap.put(0x0080, "DeLorme Publishing Company, Inc.");
        companyMap.put(0x0081, "WuXi Vimicro");
        companyMap.put(0x0082, "Sennheiser Communications A/S");
        companyMap.put(0x0083, "TimeKeeping Systems, Inc.");
        companyMap.put(0x0084, "Ludus Helsinki Ltd.");
        companyMap.put(0x0085, "BlueRadios, Inc.");
        companyMap.put(0x0086, "equinox AG");
        companyMap.put(0x0087, "Garmin International, Inc.");
        companyMap.put(0x0088, "Ecotest");
        companyMap.put(0x0089, "GN ReSound A/S");
        companyMap.put(0x008A, "Jawbone");
        companyMap.put(0x008B, "Topcon Positioning Systems, LLC");
        companyMap.put(0x008C, "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)");
        companyMap.put(0x008D, "Zscan Software");
        companyMap.put(0x008E, "Quintic Corp.");
        companyMap.put(0x008F, "Telit Wireless Solutions GmbH (Formerly Stollman E+V GmbH)");
        companyMap.put(0x0090, "Funai Electric Co., Ltd.");
        companyMap.put(0x0091, "Advanced PANMOBIL Systems GmbH & Co. KG");
        companyMap.put(0x0092, "ThinkOptics, Inc.");
        companyMap.put(0x0093, "Universal Electronics, Inc.");
        companyMap.put(0x0094, "Airoha Technology Corp.");
        companyMap.put(0x0095, "NEC Lighting, Ltd.");
        companyMap.put(0x0096, "ODM Technology, Inc.");
        companyMap.put(0x0097, "ConnecteDevice Ltd.");
        companyMap.put(0x0098, "zer01.tv GmbH");
        companyMap.put(0x0099, "i.Tech Dynamic Global Distribution Ltd.");
        companyMap.put(0x009A, "Alpwise");
        companyMap.put(0x009B, "Jiangsu Toppower Automotive Electronics Co., Ltd.");
        companyMap.put(0x009C, "Colorfy, Inc.");
        companyMap.put(0x009D, "Geoforce Inc.");
        companyMap.put(0x009E, "Bose Corporation");
        companyMap.put(0x009F, "Suunto Oy");
        companyMap.put(0x00A0, "Kensington Computer Products Group");
        companyMap.put(0x00A1, "SR-Medizinelektronik");
        companyMap.put(0x00A2, "Vertu Corporation Limited");
        companyMap.put(0x00A3, "Meta Watch Ltd.");
        companyMap.put(0x00A4, "LINAK A/S");
        companyMap.put(0x00A5, "OTL Dynamics LLC");
        companyMap.put(0x00A6, "Panda Ocean Inc.");
        companyMap.put(0x00A7, "Visteon Corporation");
        companyMap.put(0x00A8, "ARP Devices Limited");
        companyMap.put(0x00A9, "Magneti Marelli S.p.A");
        companyMap.put(0x00AA, "CAEN RFID srl");
        companyMap.put(0x00AB, "Ingenieur-Systemgruppe Zahn GmbH");
        companyMap.put(0x00AC, "Green Throttle Games");
        companyMap.put(0x00AD, "Peter Systemtechnik GmbH");
        companyMap.put(0x00AE, "Omegawave Oy");
        companyMap.put(0x00AF, "Cinetix");
        companyMap.put(0x00B0, "Passif Semiconductor Corp");
        companyMap.put(0x00B1, "Saris Cycling Group, Inc");
        companyMap.put(0x00B2, "Bekey A/S");
        companyMap.put(0x00B3, "Clarinox Technologies Pty. Ltd.");
        companyMap.put(0x00B4, "BDE Technology Co., Ltd.");
        companyMap.put(0x00B5, "Swirl Networks");
        companyMap.put(0x00B6, "Meso international");
        companyMap.put(0x00B7, "TreLab Ltd");
        companyMap.put(0x00B8, "Qualcomm Innovation Center, Inc. (QuIC)");
        companyMap.put(0x00B9, "Johnson Controls, Inc.");
        companyMap.put(0x00BA, "Starkey Laboratories Inc.");
        companyMap.put(0x00BB, "S-Power Electronics Limited");
        companyMap.put(0x00BC, "Ace Sensor Inc");
        companyMap.put(0x00BD, "Aplix Corporation");
        companyMap.put(0x00BE, "AAMP of America");
        companyMap.put(0x00BF, "Stalmart Technology Limited");
        companyMap.put(0x00C0, "AMICCOM Electronics Corporation");
        companyMap.put(0x00C1, "Shenzhen Excelsecu Data Technology Co.,Ltd");
        companyMap.put(0x00C2, "Geneq Inc.");
        companyMap.put(0x00C3, "adidas AG");
        companyMap.put(0x00C4, "LG Electronics");
        companyMap.put(0x00C5, "Onset Computer Corporation");
        companyMap.put(0x00C6, "Selfly BV");
        companyMap.put(0x00C7, "Quuppa Oy.");
        companyMap.put(0x00C8, "GeLo Inc");
        companyMap.put(0x00C9, "Evluma");
        companyMap.put(0x00CA, "MC10");
        companyMap.put(0x00CB, "Binauric SE");
        companyMap.put(0x00CC, "Beats Electronics");
        companyMap.put(0x00CD, "Microchip Technology Inc.");
        companyMap.put(0x00CE, "Elgato Systems GmbH");
        companyMap.put(0x00CF, "ARCHOS SA");
        companyMap.put(0x00D0, "Dexcom, Inc.");
        companyMap.put(0x00D1, "Polar Electro Europe B.V.");
        companyMap.put(0x00D2, "Dialog Semiconductor B.V.");
        companyMap.put(0x00D3, "Taixingbang Technology (HK) Co,. LTD.");
        companyMap.put(0x00D4, "Kawantech");
        companyMap.put(0x00D5, "Austco Communication Systems");
        companyMap.put(0x00D6, "Timex Group USA, Inc.");
        companyMap.put(0x00D7, "Qualcomm Technologies, Inc.");
        companyMap.put(0x00D8, "Qualcomm Connected Experiences, Inc.");
        companyMap.put(0x00D9, "Voyetra Turtle Beach");
        companyMap.put(0x00DA, "txtr GmbH");
        companyMap.put(0x00DB, "Biosentronics");
        companyMap.put(0x00DC, "Procter & Gamble");
        companyMap.put(0x00DD, "Hosiden Corporation");
        companyMap.put(0x00DE, "Muzik LLC");
        companyMap.put(0x00DF, "Misfit Wearables Corp");
        companyMap.put(0x00E0, "Google");
        companyMap.put(0x00E1, "Danlers Ltd");
        companyMap.put(0x00E2, "Semilink Inc");
        companyMap.put(0x00E3, "inMusic Brands, Inc");
        companyMap.put(0x00E4, "L.S. Research Inc.");
        companyMap.put(0x00E5, "Eden Software Consultants Ltd.");
        companyMap.put(0x00E6, "Freshtemp");
        companyMap.put(0x00E7, "KS Technologies");
        companyMap.put(0x00E8, "ACTS Technologies");
        companyMap.put(0x00E9, "Vtrack Systems");
        companyMap.put(0x00EA, "Nielsen-Kellerman Company");
        companyMap.put(0x00EB, "Server Technology, Inc.");
        companyMap.put(0x00EC, "BioResearch Associates");
        companyMap.put(0x00ED, "Jolly Logic, LLC");
        companyMap.put(0x00EE, "Above Average Outcomes, Inc.");
        companyMap.put(0x00EF, "Bitsplitters GmbH");
        companyMap.put(0x00F0, "PayPal, Inc.");
        companyMap.put(0x00F1, "Witron Technology Limited");
        companyMap.put(0x00F2, "Aether Things Inc. (formerly Morse Project Inc.)");
        companyMap.put(0x00F3, "Kent Displays Inc.");
        companyMap.put(0x00F4, "Nautilus Inc.");
        companyMap.put(0x00F5, "Smartifier Oy");
        companyMap.put(0x00F6, "Elcometer Limited");
        companyMap.put(0x00F7, "VSN Technologies Inc.");
        companyMap.put(0x00F8, "AceUni Corp., Ltd.");
        companyMap.put(0x00F9, "StickNFind");
        companyMap.put(0x00FA, "Crystal Code AB");
        companyMap.put(0x00FB, "KOUKAAM a.s.");
        companyMap.put(0x00FC, "Delphi Corporation");
        companyMap.put(0x00FD, "ValenceTech Limited");
        companyMap.put(0x00FE, "Reserved");
        companyMap.put(0x00FF, "Typo Products, LLC");
        companyMap.put(0x0100, "TomTom International BV");
        companyMap.put(0x0101, "Fugoo, Inc");
        companyMap.put(0x0102, "Keiser Corporation");
        companyMap.put(0x0103, "Bang & Olufsen A/S");
        companyMap.put(0x0104, "PLUS Locations Systems Pty Ltd");
        companyMap.put(0x0105, "Ubiquitous Computing Technology Corporation");
        companyMap.put(0x0106, "Innovative Yachtter Solutions");
        companyMap.put(0x0107, "William Demant Holding A/S");
        companyMap.put(0x0108, "Chicony Electronics Co., Ltd.");
        companyMap.put(0x0109, "Atus BV");
        companyMap.put(0x010A, "Codegate Ltd.");
        companyMap.put(0x010B, "ERi, Inc.");
        companyMap.put(0x010C, "Transducers Direct, LLC");
        companyMap.put(0x010D, "Fujitsu Ten Limited");
        companyMap.put(0x010E, "Audi AG");
        companyMap.put(0x010F, "HiSilicon Technologies Co., Ltd.");
        companyMap.put(0x0110, "Nippon Seiki Co., Ltd.");
        companyMap.put(0x0111, "Steelseries ApS");
        companyMap.put(0x0112, "Visybl Inc.");
        companyMap.put(0x0113, "Openbrain Technologies, Co., Ltd.");
        companyMap.put(0x0114, "Xensr");
        companyMap.put(0x0115, "e.solutions");
        companyMap.put(0x0116, "1OAK Technologies");
        companyMap.put(0x0117, "Wimoto Technologies Inc");
        companyMap.put(0x0118, "Radius Networks, Inc.");
        companyMap.put(0x0119, "Wize Technology Co., Ltd.");
        companyMap.put(0x011A, "Qualcomm Labs, Inc.");
        companyMap.put(0x011B, "Aruba Networks");
        companyMap.put(0x011C, "Baidu");
        companyMap.put(0x011D, "Arendi AG");
        companyMap.put(0x011E, "Skoda Auto a.s.");
        companyMap.put(0x011F, "Volkswagen AG");
        companyMap.put(0x0120, "Porsche AG");
        companyMap.put(0x0121, "Sino Wealth Electronic Ltd.");
        companyMap.put(0x0122, "AirTurn, Inc.");
        companyMap.put(0x0123, "Kinsa, Inc.");
        companyMap.put(0x0124, "HID Global");
        companyMap.put(0x0125, "SEAT es");
        companyMap.put(0x0126, "Promethean Ltd.");
        companyMap.put(0x0127, "Salutica Allied Solutions");
        companyMap.put(0x0128, "GPSI Group Pty Ltd");
        companyMap.put(0x0129, "Nimble Devices Oy");
        companyMap.put(0x012A, "Changzhou Yongse Infotech Co., Ltd");
        companyMap.put(0x012B, "SportIQ");
        companyMap.put(0x012C, "TEMEC Instruments B.V.");
        companyMap.put(0x012D, "Sony Corporation");
        companyMap.put(0x012E, "ASSA ABLOY");
        companyMap.put(0x012F, "Clarion Co., Ltd.");
        companyMap.put(0x0130, "Warehouse Innovations");
        companyMap.put(0x0131, "Cypress Semiconductor Corporation");
        companyMap.put(0x0132, "MADS Inc");
        companyMap.put(0x0133, "Blue Maestro Limited");
        companyMap.put(0x0134, "Resolution Products, Inc.");
        companyMap.put(0x0135, "Airewear LLC");
        companyMap.put(0x0136, "Seed Labs, Inc. (formerly ETC sp. z.o.o.)");
        companyMap.put(0x0137, "Prestigio Plaza Ltd.");
        companyMap.put(0x0138, "NTEO Inc.");
        companyMap.put(0x0139, "Focus Systems Corporation");
        companyMap.put(0x013A, "Tencent Holdings Limited");
        companyMap.put(0x013B, "Allegion");
        companyMap.put(0x013C, "Murata Manufacuring Co., Ltd.");
        companyMap.put(0x013E, "Nod, Inc.");
        companyMap.put(0x013F, "B&B Manufacturing Company");
        companyMap.put(0x0140, "Alpine Electronics (China) Co., Ltd");
        companyMap.put(0x0141, "FedEx Services");
        companyMap.put(0x0142, "Grape Systems Inc.");
        companyMap.put(0x0143, "Bkon Connect");
        companyMap.put(0x0144, "Lintech GmbH");
        companyMap.put(0x0145, "Novatel Wireless");
        companyMap.put(0x0146, "Ciright");
        companyMap.put(0x0147, "Mighty Cast, Inc.");
        companyMap.put(0x0148, "Ambimat Electronics");
        companyMap.put(0x0149, "Perytons Ltd.");
        companyMap.put(0x014A, "Tivoli Audio, LLC");
        companyMap.put(0x014B, "Master Lock");
        companyMap.put(0x014C, "Mesh-Net Ltd");
        companyMap.put(0x014D, "Huizhou Desay SV Automotive CO., LTD.");
        companyMap.put(0x014E, "Tangerine, Inc.");
        companyMap.put(0x014F, "B&W Group Ltd.");
        companyMap.put(0x0150, "Pioneer Corporation");
        companyMap.put(0x0151, "OnBeep");
        companyMap.put(0x0152, "Vernier Software & Technology");
        companyMap.put(0x0153, "ROL Ergo");
        companyMap.put(0x0154, "Pebble Technology");
        companyMap.put(0x0155, "NETATMO");
        companyMap.put(0x0156, "Accumulate AB");
        companyMap.put(0x0157, "Anhui Huami Information Technology Co., Ltd.");
        companyMap.put(0x0158, "Inmite s.r.o.");
        companyMap.put(0x0159, "ChefSteps, Inc.");
        companyMap.put(0x015A, "micas AG");
        companyMap.put(0x015B, "Biomedical Research Ltd.");
        companyMap.put(0x015C, "Pitius Tec S.L.");
        companyMap.put(0x015D, "Estimote, Inc.");
        companyMap.put(0x015E, "Unikey Technologies, Inc.");
        companyMap.put(0x015F, "Timer Cap Co.");
        companyMap.put(0x0160, "AwoX");
        companyMap.put(0x0161, "yikes");
        companyMap.put(0x0162, "MADSGlobal NZ Ltd.");
        companyMap.put(0x0163, "PCH International");
        companyMap.put(0x0164, "Qingdao Yeelink Information Technology Co., Ltd.");
        companyMap.put(0x0165, "Milwaukee Tool (formerly Milwaukee Electric Tools)");
        companyMap.put(0x0166, "MISHIK Pte Ltd");
        companyMap.put(0x0167, "Bayer HealthCare");
        companyMap.put(0x0168, "Spicebox LLC");
        companyMap.put(0x0169, "emberlight");
        companyMap.put(0x016A, "Cooper-Atkins Corporation");
        companyMap.put(0x016B, "Qblinks");
        companyMap.put(0x016C, "MYSPHERA");
        companyMap.put(0x016D, "LifeScan Inc");
        companyMap.put(0x016E, "Volantic AB");
        companyMap.put(0x016F, "Podo Labs, Inc");
        companyMap.put(0x0170, "F. Hoffmann-La Roche AG");
        companyMap.put(0x0171, "Amazon Fulfillment Service");
        companyMap.put(0x0172, "Connovate Technology Private Limited");
        companyMap.put(0x0173, "Kocomojo, LLC");
        companyMap.put(0x0174, "Everykey LLC");
        companyMap.put(0x0175, "Dynamic Controls");
        companyMap.put(0x0176, "SentriLock");
        companyMap.put(0x0177, "I-SYST inc.");
        companyMap.put(0x0178, "CASIO COMPUTER CO., LTD.");
        companyMap.put(0x0179, "LAPIS Semiconductor Co., Ltd.");
        companyMap.put(0x017A, "Telemonitor, Inc.");
        companyMap.put(0x017B, "taskit GmbH");
        companyMap.put(0x017C, "Daimler AG");
        companyMap.put(0x017D, "BatAndCat");
        companyMap.put(0x017E, "BluDotz Ltd");
        companyMap.put(0x017F, "XTel ApS");
        companyMap.put(0x0180, "Gigaset Communications GmbH");
        companyMap.put(0x0181, "Gecko Health Innovations, Inc.");
        companyMap.put(0x0182, "HOP Ubiquitous");
        companyMap.put(0x0183, "To Be Assigned");
        companyMap.put(0x0184, "Nectar");
        companyMap.put(0x0185, "bel'apps LLC");
        companyMap.put(0x0186, "CORE Lighting Ltd");
        companyMap.put(0x0187, "Seraphim Sense Ltd");
        companyMap.put(0x0188, "Unico RBC");
        companyMap.put(0x0189, "Physical Enterprises Inc.");
        companyMap.put(0x018A, "Able Trend Technology Limited");
        companyMap.put(0x018B, "Konica Minolta, Inc.");
        companyMap.put(0x018C, "Wilo SE");
        companyMap.put(0x018D, "Extron Design Services");
        companyMap.put(0x018E, "Fitbit, Inc.");
        companyMap.put(0x018F, "Fireflies Systems");
        companyMap.put(0x0190, "Intelletto Technologies Inc.");
        companyMap.put(0x0191, "FDK CORPORATION");
        companyMap.put(0x0192, "Cloudleaf, Inc");
        companyMap.put(0x0193, "Maveric Automation LLC");
        companyMap.put(0x0194, "Acoustic Stream Corporation");
        companyMap.put(0x0195, "Zuli");
        companyMap.put(0x0196, "Paxton Access Ltd");
        companyMap.put(0x0197, "WiSilica Inc");
        companyMap.put(0x0198, "VENGIT Korlátolt Felelősségű Társaság");
        companyMap.put(0x0199, "SALTO SYSTEMS S.L.");
        companyMap.put(0x019A, "TRON Forum (formerly T-Engine Forum)");
        companyMap.put(0x019B, "CUBETECH s.r.o.");
        companyMap.put(0x019C, "Cokiya Incorporated");
        companyMap.put(0x019D, "CVS Health");
        companyMap.put(0x019E, "Ceruus");
        companyMap.put(0x019F, "Strainstall Ltd");
        companyMap.put(0x01A0, "Channel Enterprises (HK) Ltd.");
        companyMap.put(0x01A1, "FIAMM");
        companyMap.put(0x01A2, "GIGALANE.CO.,LTD");
        companyMap.put(0x01A3, "EROAD");
        companyMap.put(0x01A4, "Mine Safety Appliances");
        companyMap.put(0x01A5, "Icon Health and Fitness");
        companyMap.put(0x01A6, "Asandoo GmbH");
        companyMap.put(0x01A7, "ENERGOUS CORPORATION");
        companyMap.put(0x01A8, "Taobao");
        companyMap.put(0x01A9, "Canon Inc.");
        companyMap.put(0x01AA, "Geophysical Technology Inc.");
        companyMap.put(0x01AB, "Facebook, Inc.");
        companyMap.put(0x01AC, "Nipro Diagnostics, Inc.");
        companyMap.put(0x01AD, "FlightSafety International");
        companyMap.put(0x01AE, "Earlens Corporation");
        companyMap.put(0x01AF, "Sunrise Micro Devices, Inc.");
        companyMap.put(0x01B0, "Star Micronics Co., Ltd.");
        companyMap.put(0x01B1, "Netizens Sp. z o.o.");
        companyMap.put(0x01B2, "Nymi Inc.");
        companyMap.put(0x01B3, "Nytec, Inc.");
        companyMap.put(0x01B4, "Trineo Sp. z o.o.");
        companyMap.put(0x01B5, "Nest Labs Inc.");
        companyMap.put(0x01B6, "LM Technologies Ltd");
        companyMap.put(0x01B7, "General Electric Company");
        companyMap.put(0x01B8, "i+D3 S.L.");
        companyMap.put(0x01B9, "HANA Micron");
        companyMap.put(0x01BA, "Stages Cycling LLC");
        companyMap.put(0x01BB, "Cochlear Bone Anchored Solutions AB");
        companyMap.put(0x01BC, "SenionLab AB");
        companyMap.put(0x01BD, "Syszone Co., Ltd");
        companyMap.put(0x01BE, "Pulsate Mobile Ltd.");
        companyMap.put(0x01BF, "Hong Kong HunterSun Electronic Limited");
        companyMap.put(0x01C0, "pironex GmbH");
        companyMap.put(0x01C1, "BRADATECH Corp.");
        companyMap.put(0x01C2, "Transenergooil AG");
        companyMap.put(0x01C3, "Bunch");
        companyMap.put(0x01C4, "DME Microelectronics");
        companyMap.put(0x01C5, "Bitcraze AB");
        companyMap.put(0x01C6, "HASWARE Inc.");
        companyMap.put(0x01C7, "Abiogenix Inc.");
        companyMap.put(0x01C8, "Poly-Control ApS");
        companyMap.put(0x01C9, "Avi-on");
        companyMap.put(0x01CA, "Laerdal Medical AS");
        companyMap.put(0x01CB, "Fetch My Pet");
        companyMap.put(0x01CC, "Sam Labs Ltd.");
        companyMap.put(0x01CD, "Chengdu Synwing Technology Ltd");
        companyMap.put(0x01CE, "HOUWA SYSTEM DESIGN, k.k.");
        companyMap.put(0x01CF, "BSH");
        companyMap.put(0x01D0, "Primus Inter Pares Ltd");
        companyMap.put(0x01D1, "August");
        companyMap.put(0x01D2, "Gill Electronics");
        companyMap.put(0x01D3, "Sky Wave Design");
        companyMap.put(0x01D4, "Newlab S.r.l.");
        companyMap.put(0x01D5, "ELAD srl");
        companyMap.put(0x01D6, "G-wearables inc.");
        companyMap.put(0x01D7, "Squadrone Systems Inc.");
        companyMap.put(0x01D8, "Code Corporation");
        companyMap.put(0x01D9, "Savant Systems LLC");
        companyMap.put(0x01DA, "Logitech International SA");
        companyMap.put(0x01DB, "Innblue Consulting");
        companyMap.put(0x01DC, "iParking Ltd.");
        companyMap.put(0x01DD, "Koninklijke Philips Electronics N.V.");
        companyMap.put(0x01DE, "Minelab Electronics Pty Limited");
        companyMap.put(0x01DF, "Bison Group Ltd.");
        companyMap.put(0x01E0, "Widex A/S");
        companyMap.put(0x01E1, "Jolla Ltd");
        companyMap.put(0x01E2, "Lectronix, Inc.");
        companyMap.put(0x01E3, "Caterpillar Inc");
        companyMap.put(0x01E4, "Freedom Innovations");
        companyMap.put(0x01E5, "Dynamic Devices Ltd");
        companyMap.put(0x01E6, "Technology Solutions (UK) Ltd");
        companyMap.put(0x01E7, "IPS Group Inc.");
        companyMap.put(0x01E8, "STIR");
        companyMap.put(0x01E9, "Sano, Inc");
        companyMap.put(0x01EA, "Advanced Application Design, Inc.");
        companyMap.put(0x01EB, "AutoMap LLC");
        companyMap.put(0x01EC, "Spreadtrum Communications Shanghai Ltd");
        companyMap.put(0x01ED, "CuteCircuit LTD");
        companyMap.put(0x01EE, "Valeo Service");
        companyMap.put(0x01EF, "Fullpower Technologies, Inc.");
        companyMap.put(0x01F0, "KloudNation");
        companyMap.put(0x01F1, "Zebra Technologies Corporation");
        companyMap.put(0x01F2, "Itron, Inc.");
        companyMap.put(0x01F3, "The University of Tokyo");
        companyMap.put(0x01F4, "UTC Fire and Security");
        companyMap.put(0x01F5, "Cool Webthings Limited");
        companyMap.put(0x01F6, "DJO Global");
        companyMap.put(0x01F7, "Gelliner Limited");
        companyMap.put(0x01F8, "Anyka (Guangzhou) Microelectronics Technology Co, LTD");
        companyMap.put(0x01F9, "Medtronic, Inc.");
        companyMap.put(0x01FA, "Gozio, Inc.");
        companyMap.put(0x01FB, "Form Lifting, LLC");
        companyMap.put(0x01FC, "Wahoo Fitness, LLC");
        companyMap.put(0x01FD, "Kontakt Micro-Location Sp. z o.o.");
        companyMap.put(0x01FE, "Radio System Corporation");
        companyMap.put(0x01FF, "Freescale Semiconductor, Inc.");
        companyMap.put(0x0200, "Verifone Systems PTe Ltd. Taiwan Branch");
        companyMap.put(0x0201, "AR Timing");
        companyMap.put(0x0202, "Rigado LLC");
        companyMap.put(0x0203, "Kemppi Oy");
        companyMap.put(0x0204, "Tapcentive Inc.");
        companyMap.put(0x0205, "Smartbotics Inc.");
        companyMap.put(0x0206, "Otter Products, LLC");
        companyMap.put(0x0207, "STEMP Inc.");
        companyMap.put(0x0208, "LumiGeek LLC");
        companyMap.put(0x0209, "InvisionHeart Inc.");
        companyMap.put(0x020A, "Macnica Inc. ");
        companyMap.put(0x020B, "Jaguar Land Rover Limited");
        companyMap.put(0x020C, "CoroWare Technologies, Inc");
        companyMap.put(0x020D, "Simplo Technology Co., LTD");
        companyMap.put(0x020E, "Omron Healthcare Co., LTD");
        companyMap.put(0x020F, "Comodule GMBH");
        companyMap.put(0x0210, "ikeGPS");
        companyMap.put(0x0211, "Telink Semiconductor Co. Ltd");
        companyMap.put(0x0212, "Interplan Co., Ltd");
        companyMap.put(0x0213, "Wyler AG");
        companyMap.put(0x0214, "IK Multimedia Production srl");
        companyMap.put(0x0215, "Lukoton Experience Oy");
        companyMap.put(0x0216, "MTI Ltd");
        companyMap.put(0x0217, "Tech4home, Lda");
        companyMap.put(0x0218, "Hiotech AB");
        companyMap.put(0x0219, "DOTT Limited");
        companyMap.put(0x021A, "Blue Speck Labs, LLC");
        companyMap.put(0x021B, "Cisco Systems Inc");
        companyMap.put(0x021C, "Mobicomm Inc");
        companyMap.put(0x021D, "Edamic");
        companyMap.put(0x021E, "Goodnet Ltd");
        companyMap.put(0x021F, "Luster Leaf Products Inc");
        companyMap.put(0x0220, "Manus Machina BV");
        companyMap.put(0x0221, "Mobiquity Networks Inc");
        companyMap.put(0x0222, "Praxis Dynamics");
        companyMap.put(0x0223, "Philip Morris Products S.A.");
        companyMap.put(0x0224, "Comarch SA");
        companyMap.put(0x0225, "Nestlé Nespresso S.A.");
        companyMap.put(0x0226, "Merlinia A/S");
        companyMap.put(0x0227, "LifeBEAM Technologies");
        companyMap.put(0x0228, "Twocanoes Labs, LLC");
        companyMap.put(0x0229, "Muoverti Limited");
        companyMap.put(0X022A, "Stamer Musikanlagen GMBH");
        companyMap.put(0x022B, "Tesla Motors");
        companyMap.put(0x022C, "Pharynks Corporation");
        companyMap.put(0x022D, "Lupine");
        companyMap.put(0x022E, "Siemens AG");
        companyMap.put(0x022F, "Huami (Shanghai) Culture Communication CO., LTD");
        companyMap.put(0x0230, "Foster Electric Company, Ltd");
        companyMap.put(0x0231, "ETA SA");
        companyMap.put(0x0232, " x-Senso Solutions Kft");
        companyMap.put(0x0233, " Shenzhen SuLong Communication Ltd");
        companyMap.put(0x0234, " FengFan (BeiJing) Technology Co, Ltd");
        companyMap.put(0x0235, " Qrio Inc");
        companyMap.put(0x0236, " Pitpatpet Ltd");
        companyMap.put(0x0237, " MSHeli s.r.l.");
        companyMap.put(0x0238, "Trakm8 Ltd");
        companyMap.put(0x0239, "JIN CO, Ltd");
        companyMap.put(0x023A, "Alatech Technology");
        companyMap.put(0x023B, "Beijing CarePulse Electronic Technology Co, Ltd");
        companyMap.put(0x023C, "Awarepoint");
        companyMap.put(0x023D, "ViCentra B.V.");
        companyMap.put(0x023E, "Raven Industries");
        companyMap.put(0x023F, "WaveWare Technologies");
        companyMap.put(0x0240, "Argenox Technologies");
        companyMap.put(0x0241, "Bragi GmbH");
        companyMap.put(0x0242, "16Lab Inc");
        companyMap.put(0x0243, "Masimo Corp");
        companyMap.put(0x0244, "Iotera Inc.");
        companyMap.put(0x0245, "Endress+Hauser");
        companyMap.put(0x0246, "ACKme Networks, Inc.");
        companyMap.put(0x0247, "FiftyThree Inc.");
        companyMap.put(0x0248, "Parker Hannifin Corp");
        companyMap.put(0x0249, "Transcranial Ltd");
        companyMap.put(0x024A, "Uwatec AG");
        companyMap.put(0x024B, "Orlan LLC");
        companyMap.put(0x024C, "Blue Clover Devices");
        companyMap.put(0x024D, "M-Way Solutions GmbH");
        companyMap.put(0x024E, "Microtronics Engineering GmbH");
        companyMap.put(0x024F, "Schneider Schreibgeräte GmbH");
        companyMap.put(0x0250, "Sapphire Circuits LLC");
        companyMap.put(0x0251, "Lumo Bodytech Inc.");
        companyMap.put(0x0252, "UKC Technosolution");
        companyMap.put(0x0253, "Xicato Inc.");
        companyMap.put(0x0254, "Playbrush");
        companyMap.put(0x0255, "Dai Nippon Printing Co., Ltd.");
        companyMap.put(0x0256, "G24 Power Limited");
        companyMap.put(0x0257, "AdBabble Local Commerce Inc.");
        companyMap.put(0x0258, "Devialet SA");
        companyMap.put(0x0259, "ALTYOR");
        companyMap.put(0x025A, "University of Applied Sciences Valais/Haute Ecole Valaisanne");
        companyMap.put(0x025B, "Five Interactive, LLC dba Zendo");
        companyMap.put(0x025C, "NetEase (Hangzhou) Network co.Ltd.");
        companyMap.put(0x025D, "Lexmark International Inc.");
        companyMap.put(0x025E, "Fluke Corporation");
        companyMap.put(0x025F, "Yardarm Technologies");
        companyMap.put(0x0260, "SensaRx");
        companyMap.put(0x0261, "SECVRE GmbH");
        companyMap.put(0x0262, "Glacial Ridge Technologies");
        companyMap.put(0x0263, "Identiv, Inc.");
        companyMap.put(0x0264, "DDS, Inc.");
        companyMap.put(0x0265, "SMK Corporation");
        companyMap.put(0x0266, "Schawbel Technologies LLC");
        companyMap.put(0x0267, "XMI Systems SA");
        companyMap.put(0x0268, "Cerevo");
        companyMap.put(0x0269, "Torrox GmbH & Co KG");
        companyMap.put(0x026A, "Gemalto");
        companyMap.put(0x026B, "DEKA Research & Development Corp.");
        companyMap.put(0x026C, "Domster Tadeusz Szydlowski");
        companyMap.put(0x026D, "Technogym SPA");
        companyMap.put(0x026E, "FLEURBAEY BVBA");
        companyMap.put(0x026F, "Aptcode Solutions");
        companyMap.put(0x0270, "LSI ADL Technology");
        companyMap.put(0x0271, "Animas Corp");
        companyMap.put(0x0272, "Alps Electric Co., Ltd.");
        companyMap.put(0x0273, "OCEASOFT");
        companyMap.put(0x0274, "Motsai Research");
        companyMap.put(0x0275, "Geotab");
        companyMap.put(0x0276, "E.G.O. Elektro-Gerätebau GmbH");
        companyMap.put(0x0277, "bewhere inc");
        companyMap.put(0x0278, "Johnson Outdoors Inc");
        companyMap.put(0x0279, "steute Schaltgerate GmbH & Co. KG");
        companyMap.put(0x027A, "Ekomini inc.");
        companyMap.put(0x027B, "DEFA AS");
        companyMap.put(0x027C, "Aseptika Ltd");
        companyMap.put(0x027D, "HUAWEI Technologies Co., Ltd. ( 华为技术有限公司 )");
        companyMap.put(0x027E, "HabitAware, LLC");
        companyMap.put(0x027F, "ruwido austria gmbh");
        companyMap.put(0x0280, "ITEC corporation");
        companyMap.put(0x0281, "StoneL");
        companyMap.put(0x0282, "Sonova AG");
        companyMap.put(0x0283, "Maven Machines, Inc.");
        companyMap.put(0x0284, "Synapse Electronics");
        companyMap.put(0x0285, "Standard Innovation Inc.");
        companyMap.put(0x0286, "RF Code, Inc.");
        companyMap.put(0x0287, "Wally Ventures S.L.");
        companyMap.put(0x0288, "Willowbank Electronics Ltd");
        companyMap.put(0x0289, "SK Telecom");
        companyMap.put(0x028A, "Jetro AS");
        companyMap.put(0x028B, "Code Gears LTD");
        companyMap.put(0x028C, "NANOLINK APS");
        companyMap.put(0x028D, "IF, LLC");
        companyMap.put(0x028E, "RF Digital Corp");
        companyMap.put(0x028F, "Church & Dwight Co., Inc");
        companyMap.put(0x0290, "Multibit Oy");
        companyMap.put(0x0291, "CliniCloud Inc");
        companyMap.put(0x0292, "SwiftSensors");
        companyMap.put(0x0293, "Blue Bite");
        companyMap.put(0x0294, "ELIAS GmbH");
        companyMap.put(0x0295, "Sivantos GmbH");
        companyMap.put(0x0296, "Petzl");
        companyMap.put(0x0297, "storm power ltd");
        companyMap.put(0x0298, "EISST Ltd");
        companyMap.put(0x0299, "Inexess Technology Simma KG");
        companyMap.put(0x029A, "Currant, Inc.");
        companyMap.put(0x029B, "C2 Development, Inc.");
        companyMap.put(0x029C, "Blue Sky Scientific, LLC");
        companyMap.put(0x029D, "ALOTTAZS LABS, LLC");
        companyMap.put(0x029E, "Kupson spol. s r.o.");
        companyMap.put(0x029F, "Areus Engineering GmbH");
        companyMap.put(0x02A0, "Impossible Camera GmbH");
        companyMap.put(0x02A1, "InventureTrack Systems");
        companyMap.put(0x02A2, "LockedUp");
        companyMap.put(0x02A3, "Itude");
        companyMap.put(0x02A4, "Pacific Lock Company");
        companyMap.put(0x02A5, "Tendyron Corporation ( 天地融科技股份有限公司 )");
        companyMap.put(0x02A6, "Robert Bosch GmbH");
        companyMap.put(0x02A7, "Illuxtron international B.V.");
        companyMap.put(0x02A8, "miSport Ltd.");
        companyMap.put(0x02A9, "Chargelib");
        companyMap.put(0x02AA, "Doppler Lab");
        companyMap.put(0x02AB, "BBPOS Limited");
        companyMap.put(0x02AC, "RTB Elektronik GmbH & Co. KG");
        companyMap.put(0x02AD, "Rx Networks, Inc.");
        companyMap.put(0x02AE, "WeatherFlow, Inc.");
        companyMap.put(0x02AF, "Technicolor USA Inc.");
        companyMap.put(0x02B0, "Bestechnic(Shanghai),Ltd");
        companyMap.put(0x02B1, "Raden Inc");
        companyMap.put(0x02B2, "JouZen Oy");
        companyMap.put(0x02B3, "CLABER S.P.A.");
        companyMap.put(0x02B4, "Hyginex, Inc.");
        companyMap.put(0x02B5, "HANSHIN ELECTRIC RAILWAY CO.,LTD.");
        companyMap.put(0x02B6, "Schneider Electric");
        companyMap.put(0x02B7, "Oort Technologies LLC");
        companyMap.put(0x02B8, "Chrono Therapeutics");
        companyMap.put(0x02B9, "Rinnai Corporation");
        companyMap.put(0x02BA, "Swissprime Technologies AG");
        companyMap.put(0x02BB, "Koha.,Co.Ltd");
        companyMap.put(0x02BC, "Genevac Ltd");
        companyMap.put(0x02BD, "Chemtronics");
        companyMap.put(0x02BE, "Seguro Technology Sp. z o.o.");
        companyMap.put(0x02BF, "Redbird Flight Simulations");
        companyMap.put(0x02C0, "Dash Robotics");
        companyMap.put(0x02C1, "LINE Corporation");
        companyMap.put(0x02C2, "Guillemot Corporation");
        companyMap.put(0x02C3, "Techtronic Power Tools Technology Limited");
        companyMap.put(0x02C4, "Wilson Sporting Goods");
        companyMap.put(0x02C5, "Lenovo (Singapore) Pte Ltd. ( 联想（新加坡） )");
        companyMap.put(0x02C6, "Ayatan Sensors");
        companyMap.put(0x02C7, "Electronics Tomorrow Limited");
        companyMap.put(0x02C8, "VASCO Data Security International, Inc.");
        companyMap.put(0x02C9, "PayRange Inc.");
        companyMap.put(0x02CA, "ABOV Semiconductor");
        companyMap.put(0x02CB, "AINA-Wireless Inc.");
        companyMap.put(0x02CC, "Eijkelkamp Soil & Water");
        companyMap.put(0x02CD, "BMA ergonomics b.v.");
        companyMap.put(0x02CE, "Teva Branded Pharmaceutical Products R&D, Inc.");
        companyMap.put(0x02CF, "Anima");
        companyMap.put(0x02D0, "3M");
        companyMap.put(0x02D1, "Empatica Srl");
        companyMap.put(0x02D2, "Afero, Inc.");
        companyMap.put(0x02D3, "Powercast Corporation");
        companyMap.put(0x02D4, "Secuyou ApS");
        companyMap.put(0x02D5, "OMRON Corporation");
        companyMap.put(0x02D6, "Send Solutions");
        companyMap.put(0x02D7, "NIPPON SYSTEMWARE CO.,LTD.");
        companyMap.put(0x02D8, "Neosfar");
        companyMap.put(0x02D9, "Fliegl Agrartechnik GmbH");
        companyMap.put(0x02DA, "Gilvader");
        companyMap.put(0x02DB, "Digi International Inc (R)");
        companyMap.put(0x02DC, "DeWalch Technologies, Inc.");
        companyMap.put(0x02DD, "Flint Rehabilitation Devices, LLC");
        companyMap.put(0x02DE, "Samsung SDS Co., Ltd.");
        companyMap.put(0x02DF, "Blur Product Development");
        companyMap.put(0x02E0, "University of Michigan");
        companyMap.put(0x02E1, "Victron Energy BV");
        companyMap.put(0x02E2, "NTT docomo");
        companyMap.put(0x02E3, "Carmanah Technologies Corp.");
        companyMap.put(0x02E4, "Bytestorm Ltd.");
        companyMap.put(0x02E5, "Espressif Incorporated ( 乐鑫信息科技(上海)有限公司 )");
        companyMap.put(0x02E6, "Unwire");
        companyMap.put(0x02E7, "Connected Yard, Inc.");
        companyMap.put(0x02E8, "American Music Environments");
        companyMap.put(0x02E9, "Sensogram Technologies, Inc.");
        companyMap.put(0x02EA, "Fujitsu Limited");
        companyMap.put(0x02EB, "Ardic Technology");
        companyMap.put(0x02EC, "Delta Systems, Inc");
        companyMap.put(0x02ED, "HTC Corporation");
        companyMap.put(0x02EE, "Citizen Holdings Co., Ltd.");
        companyMap.put(0x02EF, "SMART-INNOVATION.inc");
        companyMap.put(0x02F0, "Blackrat Software");
        companyMap.put(0x02F1, "The Idea Cave, LLC");
        companyMap.put(0x02F2, "GoPro, Inc.");
        companyMap.put(0x02F3, "AuthAir, Inc");
        companyMap.put(0x02F4, "Vensi, Inc.");
        companyMap.put(0x02F5, "Indagem Tech LLC");
        companyMap.put(0x02F6, "Intemo Technologies");
        companyMap.put(0x02F7, "DreamVisions co., Ltd.");
        companyMap.put(0x02F8, "Runteq Oy Ltd ");
        companyMap.put(0x02F9, "IMAGINATION TECHNOLOGIES LTD ");
        companyMap.put(0x02FA, "CoSTAR Technologies ");
        companyMap.put(0x02FB, "Clarius Mobile Health Corp. ");
        companyMap.put(0x02FC, "Shanghai Frequen Microelectronics Co., Ltd. ");
        companyMap.put(0x02FD, "Uwanna, Inc. ");
        companyMap.put(0x02FE, "Lierda Science & Technology Group Co., Ltd.");
        companyMap.put(0x02FF, "Silicon Laboratories");
        companyMap.put(0x0300, "World Moto Inc.");
        companyMap.put(0x0301, "Giatec Scientific Inc.");
        companyMap.put(0x0302, "Loop Devices, Inc");
        companyMap.put(0x0303, "IACA electronique ");
        companyMap.put(0x0304, "Martians Inc ");
        companyMap.put(0x0305, "Swipp ApS ");
        companyMap.put(0x0306, "Life Laboratory Inc. ");
        companyMap.put(0x0307, "FUJI INDUSTRIAL CO.,LTD.");
        companyMap.put(0x0308, "Surefire, LLC ");
        companyMap.put(0x0309, "Dolby Labs ");
        companyMap.put(0x030A, "Ellisys ");
        companyMap.put(0x030B, "Magnitude Lighting Converters ");
        companyMap.put(0x030C, "Hilti AG ");
        companyMap.put(0x030D, "Devdata S.r.l. ");
        companyMap.put(0x030E, "Deviceworx ");
        companyMap.put(0x030F, "Shortcut Labs ");
        companyMap.put(0x0310, "SGL Italia S.r.l.");
        companyMap.put(0x0311, "PEEQ DATA");
        companyMap.put(0x0312, "Ducere Technologies Pvt Ltd");
        companyMap.put(0x0313, "DiveNav, Inc.");
        companyMap.put(0x0314, "RIIG AI Sp. z o.o.");
        companyMap.put(0x0315, "Thermo Fisher Scientific");
        companyMap.put(0x0316, "AG Measurematics Pvt. Ltd. ");
        companyMap.put(0x0317, "CHUO Electronics CO., LTD. ");
        companyMap.put(0x0318, "Aspenta International ");
        companyMap.put(0x0319, "Eugster Frismag AG ");
        companyMap.put(0x031A, "Amber wireless GmbH");
        companyMap.put(0x031B, "HQ Inc");
        companyMap.put(0x031C, "Lab Sensor Solutions");
        companyMap.put(0x031D, "Enterlab ApS");
        companyMap.put(0x031E, "Eyefi, Inc.");
        companyMap.put(0x031F, "MetaSystem S.p.A");
        companyMap.put(0x0320, "SONO ELECTRONICS. CO., LTD");
        companyMap.put(0x0321, "Jewelbots");
        companyMap.put(0x0322, "Compumedics Limited ");
        companyMap.put(0x0323, "Rotor Bike Components ");
        companyMap.put(0x0324, "Astro, Inc.");
        companyMap.put(0x0325, "Amotus Solutions ");
        companyMap.put(0x0326, "Healthwear Technologies (Changzhou)Ltd ");
        companyMap.put(0x0327, "Essex Electronics ");
        companyMap.put(0x0328, "Grundfos A/S ");
        companyMap.put(0x0329, "Eargo, Inc. ");
        companyMap.put(0x032A, "Electronic Design Lab ");
        companyMap.put(0x032B, "ESYLUX ");
        companyMap.put(0x032C, "NIPPON SMT.CO.,Ltd ");
        companyMap.put(0x032D, "BM innovations GmbH");
        companyMap.put(0x032E, "indoormap ");
        companyMap.put(0x032F, "OttoQ Inc ");
        companyMap.put(0x0330, "North Pole Engineering ");
        companyMap.put(0x0331, "3flares Technologies Inc. ");
        companyMap.put(0x0332, "Electrocompaniet A.S. ");
        companyMap.put(0x0333, "Mul-T-Lock ");
        companyMap.put(0x0334, "Corentium AS ");
        companyMap.put(0x0335, "Enlighted Inc ");
        companyMap.put(0x0336, "GISTIC ");
        companyMap.put(0x0337, "AJP2 Holdings, LLC ");
        companyMap.put(0x0338, "COBI GmbH ");
        companyMap.put(0x0339, "Blue Sky Scientific, LLC ");
        companyMap.put(0x033A, "Appception, Inc. ");
        companyMap.put(0x033B, "Courtney Thorne Limited ");
        companyMap.put(0x033C, "Virtuosys ");
        companyMap.put(0x033D, "TPV Technology Limited ");
        companyMap.put(0x033E, "Monitra SA ");
        companyMap.put(0x033F, "Automation Components, Inc. ");
        companyMap.put(0x0340, "Letsense s.r.l. ");
        companyMap.put(0x0341, "Etesian Technologies LLC ");
        companyMap.put(0x0342, "GERTEC BRASIL LTDA.");
        companyMap.put(0x0343, "Drekker Development Pty. Ltd. ");
        companyMap.put(0x0344, "Whirl Inc ");
        companyMap.put(0x0345, "Locus Positioning ");
        companyMap.put(0x0346, "Acuity Brands Lighting, Inc ");
        companyMap.put(0x0347, "Prevent Biometrics ");
        companyMap.put(0x0348, "Arioneo ");
        companyMap.put(0x0349, "VersaMe ");
        companyMap.put(0x034A, "Vaddio ");
        companyMap.put(0x034B, "Libratone A/S ");
        companyMap.put(0x034C, "HM Electronics, Inc. ");
        companyMap.put(0x034D, "TASER International, Inc. ");
        companyMap.put(0x034E, "Safe Trust Inc.");
        companyMap.put(0x034F, "Heartland Payment Systems ");
        companyMap.put(0x0350, "Bitstrata Systems Inc. ");
        companyMap.put(0x0351, "Pieps GmbH ");
        companyMap.put(0x0352, "iRiding(Xiamen)Technology Co.,Ltd. ");
        companyMap.put(0x0353, "Alpha Audiotronics, Inc. ");
        companyMap.put(0x0354, "TOPPAN FORMS CO.,LTD. ");
        companyMap.put(0x0355, "Sigma Designs, Inc. ");
        companyMap.put(0x0356, "Spectrum Brands, Inc.");
        companyMap.put(0x0357, "Polymap Wireless ");
        companyMap.put(0x0358, "MagniWare Ltd. ");
        companyMap.put(0x0359, "Novotec Medical GmbH ");
        companyMap.put(0x035A, "Medicom Innovation Partner a/s ");
        companyMap.put(0x035B, "Matrix Inc. ");
        companyMap.put(0x035C, "Eaton Corporation ");
        companyMap.put(0x035D, "KYS ");
        companyMap.put(0x035E, "Naya Health, Inc. ");
        companyMap.put(0x035F, "Acromag ");
        companyMap.put(0x0360, "Insulet Corporation ");
        companyMap.put(0x0361, "Wellinks Inc. ");
        companyMap.put(0x0362, "ON Semiconductor ");
        companyMap.put(0x0363, "FREELAP SA ");
        companyMap.put(0x0364, "Favero Electronics Srl ");
        companyMap.put(0x0365, "BioMech Sensor LLC ");
        companyMap.put(0x0366, "BOLTT Sports technologies Private limited ");
        companyMap.put(0x0367, "Saphe International");
        companyMap.put(0x0368, "Metormote AB ");
        companyMap.put(0x0369, "littleBits ");
        companyMap.put(0x036A, "SetPoint Medical ");
        companyMap.put(0x036B, "BRControls Products BV ");
        companyMap.put(0x036C, "Zipcar ");
        companyMap.put(0x036D, "AirBolt Pty Ltd ");
        companyMap.put(0x036E, "KeepTruckin Inc ");
        companyMap.put(0x036F, "Motiv, Inc. ");
        companyMap.put(0x0370, "Wazombi Labs OÜ ");
        companyMap.put(0x0371, "ORBCOMM ");
        companyMap.put(0x0372, "Nixie Labs, Inc. ");
        companyMap.put(0x0373, "AppNearMe Ltd ");
        companyMap.put(0x0374, "Holman Industries ");
        companyMap.put(0x0375, "Expain AS");
        companyMap.put(0x0376, "Electronic Temperature Instruments Ltd ");
        companyMap.put(0x0377, "Plejd AB ");
        companyMap.put(0x0378, "Propeller Health ");
        companyMap.put(0x0379, "Shenzhen iMCO Electronic Technology Co.,Ltd ");
        companyMap.put(0x037A, "Algoria ");
        companyMap.put(0x037B, "Apption Labs Inc. ");
        companyMap.put(0x037C, "Cronologics Corporation ");
        companyMap.put(0x037D, "MICRODIA Ltd. ");
        companyMap.put(0x037E, "lulabytes S.L. ");
        companyMap.put(0x037F, "Nestec S.A. ");
        companyMap.put(0x0380, "LLC MEGA-F service ");
        companyMap.put(0x0381, "Sharp Corporation ");
        companyMap.put(0x0382, "Precision Outcomes Ltd ");
        companyMap.put(0x0383, "Kronos Incorporated ");
        companyMap.put(0x0384, "OCOSMOS Co., Ltd.");
        companyMap.put(0x0385, "Embedded Electronic Solutions Ltd. dba e2Solutions ");
        companyMap.put(0x0386, "Aterica Inc. ");
        companyMap.put(0x0387, "BluStor PMC, Inc. ");
        companyMap.put(0x0388, "Kapsch TrafficCom AB");
        companyMap.put(0x0389, "ActiveBlu Corporation");
        companyMap.put(0x038A, "Kohler Mira Limited");
        companyMap.put(0x038B, "Noke");
        companyMap.put(0x038C, "Appion Inc.");
        companyMap.put(0x038D, "Resmed Ltd");
        companyMap.put(0x038E, "Crownstone B.V.");
        companyMap.put(0x038F, "Xiaomi Inc.");
        companyMap.put(0x0390, "INFOTECH s.r.o.");
        companyMap.put(0x0391, "Thingsquare AB ");
        companyMap.put(0x0392, "T&D ");
        companyMap.put(0x0393, "LAVAZZA S.p.A. ");
        companyMap.put(0x0394, "Netclearance Systems, Inc. ");
        companyMap.put(0x0395, "SDATAWAY ");
        companyMap.put(0x0396, "BLOKS GmbH ");
        companyMap.put(0x0397, "LEGO System A/S ");
        companyMap.put(0x0398, "Thetatronics Ltd ");
        companyMap.put(0x0399, "Nikon Corporation ");
        companyMap.put(0x039A, "NeST ");
        companyMap.put(0x039B, "South Silicon Valley Microelectronics ");
        companyMap.put(0x039C, "ALE International ");
        companyMap.put(0x039D, "CareView Communications, Inc. ");
        companyMap.put(0x039E, "SchoolBoard Limited ");
        companyMap.put(0x039F, "Molex Corporation ");
        companyMap.put(0x03A0, "IVT Wireless Limited");
        companyMap.put(0x03A1, "Alpine Labs LLC");
        companyMap.put(0x03A2, "Candura Instruments");
        companyMap.put(0x03A3, "SmartMovt Technology Co., Ltd ");
        companyMap.put(0x03A4, "Token Zero Ltd ");
        companyMap.put(0x03A5, "ACE CAD Enterprise Co., Ltd. (ACECAD) ");
        companyMap.put(0x03A6, "Medela, Inc ");
        companyMap.put(0x03A7, "AeroScout ");
        companyMap.put(0x03A8, "Esrille Inc. ");
        companyMap.put(0x03A9, "THINKERLY SRL ");
        companyMap.put(0x03AA, "Exon Sp. z o.o. ");
        companyMap.put(0x03AB, "Meizu Technology Co., Ltd. ");
        companyMap.put(0x03AC, "Smablo LTD ");
        companyMap.put(0x03AD, "XiQ ");
        companyMap.put(0x03AE, "Allswell Inc. ");
        companyMap.put(0x03AF, "Comm-N-Sense Corp DBA Verigo ");
        companyMap.put(0x03B0, "VIBRADORM GmbH ");
        companyMap.put(0x03B1, "Otodata Wireless Network Inc. ");
        companyMap.put(0x03B2, "Propagation Systems Limited ");
        companyMap.put(0x03B3, "Midwest Instruments & Controls ");
        companyMap.put(0x03B4, "Alpha Nodus, inc. ");
        companyMap.put(0x03B5, "petPOMM, Inc ");
        companyMap.put(0x03B6, "Mattel ");
        companyMap.put(0x03B7, "Airbly Inc. ");
        companyMap.put(0x03B8, "A-Safe Limited ");
        companyMap.put(0x03B9, "FREDERIQUE CONSTANT SA ");
        companyMap.put(0x03BA, "Maxscend Microelectronics Company Limited ");
        companyMap.put(0x03BB, "Abbott Diabetes Care ");
        companyMap.put(0x03BC, "ASB Bank Ltd ");
        companyMap.put(0x03BD, "amadas ");
        companyMap.put(0x03BE, "Applied Science, Inc. ");
        companyMap.put(0x03BF, "iLumi Solutions Inc. ");
        companyMap.put(0x03C0, "Arch Systems Inc. ");
        companyMap.put(0x03C1, "Ember Technologies, Inc. ");
        companyMap.put(0x03C2, "Snapchat Inc");
        companyMap.put(0x03C3, "Casambi Technologies Oy ");
        companyMap.put(0x03C4, "Pico Technology Inc. ");
        companyMap.put(0x03C5, "St. Jude Medical, Inc. ");
        companyMap.put(0x03C6, "Intricon ");
        companyMap.put(0x03C7, "Structural Health Systems, Inc. ");
        companyMap.put(0x03C8, "Avvel International ");
        companyMap.put(0x03C9, "Gallagher Group ");
        companyMap.put(0x03CA, "In2things Automation Pvt. Ltd. ");
        companyMap.put(0x03CB, "SYSDEV Srl ");
        companyMap.put(0x03CC, "Vonkil Technologies Ltd ");
        companyMap.put(0x03CD, "Wynd Technologies, Inc. ");
        companyMap.put(0x03CE, "CONTRINEX S.A. ");
        companyMap.put(0x03CF, "MIRA, Inc. ");
        companyMap.put(0x03D0, "Watteam Ltd");
        companyMap.put(0x03D1, "Density Inc. ");
        companyMap.put(0x03D2, "IOT Pot India Private Limited ");
        companyMap.put(0x03D3, "Sigma Connectivity AB ");
        companyMap.put(0x03D4, "PEG PEREGO SPA ");
        companyMap.put(0x03D5, "Wyzelink Systems Inc. ");
        companyMap.put(0x03D6, "Yota Devices LTD ");
        companyMap.put(0x03D7, "FINSECUR ");
        companyMap.put(0x03D8, "Zen-Me Labs Ltd ");
        companyMap.put(0x03D9, "3IWare Co., Ltd. ");
        companyMap.put(0x03DA, "EnOcean GmbH ");
        companyMap.put(0x03DB, "Instabeat, Inc ");
        companyMap.put(0x03DC, "Nima Labs ");
        companyMap.put(0x03DD, "Andreas Stihl AG & Co. KG ");
        companyMap.put(0x03DE, "Nathan Rhoades LLC ");
        companyMap.put(0x03DF, "Grob Technologies, LLC ");
        companyMap.put(0x03E0, "Actions (Zhuhai) Technology Co., Limited ");
        companyMap.put(0x03E1, "SPD Development Company Ltd ");
        companyMap.put(0x03E2, "Sensoan Oy ");
        companyMap.put(0x03E3, "Qualcomm Life Inc ");
        companyMap.put(0x03E4, "Chip-ing AG ");
        companyMap.put(0x03E5, "ffly4u ");
        companyMap.put(0x03E6, "IoT Instruments Oy ");
        companyMap.put(0x03E7, "TRUE Fitness Technology ");
        companyMap.put(0x03E8, "Reiner Kartengeraete GmbH & Co. KG. ");
        companyMap.put(0x03E9, "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD. ");
        companyMap.put(0x03EA, "Hello Inc. ");
        companyMap.put(0x03EB, "Evollve Inc. ");
        companyMap.put(0x03EC, "Jigowatts Inc. ");
        companyMap.put(0x03ED, "BASIC MICRO.COM,INC. ");
        companyMap.put(0x03EE, "CUBE TECHNOLOGIES ");
        companyMap.put(0x03EF, "foolography GmbH ");
        companyMap.put(0x03F0, "CLINK ");
        companyMap.put(0x03F1, "Hestan Smart Cooking Inc. ");
        companyMap.put(0x03F2, "WindowMaster A/S ");
        companyMap.put(0x03F3, "Flowscape AB ");
        companyMap.put(0x03F4, "PAL Technologies Ltd ");
        companyMap.put(0x03F5, "WHERE, Inc. ");
        companyMap.put(0x03F6, "Iton Technology Corp. ");
        companyMap.put(0x03F7, "Owl Labs Inc. ");
        companyMap.put(0xFFFF, "DEV-COMPANY");
    }
}
